server:
  port: 8015
  servlet:
    session:
      timeout: 10
zuul:
  routes:
    api-a:
      path: /callerDemo1/**
      serviceId: callerDemo1
    api-b:
      path: /customerDemo2/**
      serviceId: customerDemo2
    api-c:
      path: /customerDemo1/**
      serviceId: customerDemo1
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
spring:
  application:
    name: zuulDemo
  datasource:
    url: jdbc:mysql://localhost:3306/cloudtest?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19950912
demo.security.jwt.secret: otherpeopledontknowit