server:
  port: 8013
spring:
  application:
    name: callerDemo1
#  activemq:
#    broker-url: tcp://127.0.0.1:61616
#    user: admin
#    password: admin
#    pool:
#      enabled: true
#      max-connections: 10
  datasource:
    url: jdbc:mysql://localhost:3306/cloudtest
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19950912
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
